spring:
  application:
    name: user-service-highavailability
  profiles:
    active: client1
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
---
spring:
  profiles: client1
server:
  port: 8881
---
spring:
  profiles: client2
server:
  port: 8882